"""Shared Prometheus instrumentation helpers.

`mount_metrics(app)` adds a GET /metrics route to any FastAPI app in the
standard Prometheus text exposition format — the same format
arena/target-app's Go /metrics handler hand-rolls (see
middleware.go's prometheusFormat()), just generated by the real
prometheus_client library instead. `observability/prometheus/prometheus.yml`
scrapes this route on whichever port each service already listens on; no
separate metrics port needed.

The metric factories (counter/histogram/gauge) exist so every service
defines its own metrics the same way, with names that follow Prometheus
convention (snake_case, unit suffix, `_total` for counters).
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, CollectorRegistry, REGISTRY, generate_latest, CONTENT_TYPE_LATEST


def mount_metrics(app, registry: CollectorRegistry | None = None):
    """Adds GET /metrics to a FastAPI app. Import and call this once,
    after building the app, in each service's build_app()."""
    from fastapi import Response
    active_registry = registry if registry is not None else REGISTRY

    @app.get("/metrics")
    def metrics_endpoint():
        return Response(generate_latest(active_registry), media_type=CONTENT_TYPE_LATEST)

    return app


def counter(name: str, description: str, labelnames: tuple = ()) -> Counter:
    return Counter(name, description, labelnames)


def histogram(name: str, description: str, labelnames: tuple = (), buckets=None) -> Histogram:
    kwargs = {"labelnames": labelnames}
    if buckets is not None:
        kwargs["buckets"] = buckets
    return Histogram(name, description, **kwargs)


def gauge(name: str, description: str, labelnames: tuple = ()) -> Gauge:
    return Gauge(name, description, labelnames)
