# Applied verbatim by blue_controller when a stronger response than
# rate-limiting is warranted but a full pod isolation isn't justified yet:
# blocks everything except traffic originating from inside the cluster.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-external-traffic
  namespace: panopticon-arena
spec:
  podSelector:
    matchLabels:
      app: target-app
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: panopticon-arena
